### ISSUE TITLE
[feature] Add details to the README

### ISSUE THREAD

**Issue by daaaayeah** [daaaayeah/oss-moayoung#41]
## ✨ 기대 결과
리드미 내용 추가 -> 지속적인 contribution 끌어내기

## ✔ 할 일
- [x] Project Structure 추가
- [x] Coding Conventions 추가 -> contributing
- [x] Commit Conventions 추가 -> contributing
- [ ] Contributors 추가 (선택)
- [x] 홈페이지 스크린샷 변경

**Comment by dayelop** [comment]
Contributors는 추후 all contributors bot 이용하여 추가 예정
